{{ $config := .Values.hermes.certs }}
kind: Ingress
apiVersion: extensions/v1beta1

metadata:
  name: hermes-api
  namespace: hermes
  {{- if .Values.hermes.certs.vice_president }}
  annotations:
    vice-president: "true"
  {{- end}}

spec:
  tls:
    - secretName: hermes-api
      hosts: [ {{ $config.domain }} ]
  rules:
    - host: {{ $config.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: hermes-api
              servicePort: 80

---

