---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-etc
  namespace: hermes
  labels:
    system: openstack
    service: audit
    component: configuration

data:
  elasticsearch.yml: |
{{ include "hermes/templates/etc/_elasticsearch.yml.tpl" . | indent 4 }}
  log4j2.properties: |
{{ include "hermes/templates/etc/_log4j2.properties.tpl" . | indent 4 }}
  jvm.options: |
{{ include "hermes/templates/etc/_jvm.options.tpl" . | indent 4 }}
