apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: es-manager
  namespace: hermes
    {{- if .Values.vice_president }}
  annotations:
    vice-president: "true"
  {{- end}}

spec:
  tls:
     - secretName: elasticsearch-manager
       hosts: [{{.Values.elk_elasticsearch_manager_endpoint_host_public}}]
  rules:
    - host: {{.Values.elk_elasticsearch_manager_endpoint_host_public}}
      http:
        paths:
        - path: /
          backend:
            serviceName: es-manager
            servicePort: {{.Values.elk_elasticsearch_manager_port_internal}}
