{{- if .Values.elk_elasticsearch_manager_tls_key }}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: elasticsearch-manager

data:
  tls.crt: {{ default "" .Values.hermes_elasticsearch_manager_tls_crt | b64enc | quote }} 
  tls.key: {{ default "" .Values.hermes_elasticsearch_manager_tls_key | b64enc | quote }}
{{- end }}