---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-manager-etc
  labels:
    system: openstack
    service: audit
    component: configuration

data:
  elasticsearch-application.conf: |
{{ include "elk/templates/etc/_application.conf.tpl" . | indent 4 }}
