apiVersion: v1
kind: Service
metadata:
  name: es-manager
  namespace: hermes
  labels:
    system: openstack
    service: audit
    component: elasticsearch
    role:  manager
spec:
  selector:
    component: elasticsearch
    role:  manager
  ports:
    - name: manager
      port: {{.Values.hermes_elasticsearch_manager_port_internal}}
