{{ if .Values.hermes.deploy_kibana }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-etc
  namespace: hermes
  labels:
    system: openstack
    service: audit
    component: configuration

data:
  kibana.yml: |
{{ include "hermes/templates/etc/_kibana.yml.tpl" . | indent 4 }}
{{ end }}
