---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-etc
  namespace: hermes
  labels:
    system: openstack
    service: audit
    component: configuration

data:
  logstash.conf: |
{{ include "hermes/templates/etc/_logstash.conf.tpl" . | indent 4 }}
  audit.json: |
{{ include "hermes/templates/etc/_audit.json.tpl" . | indent 4 }}
  logstash.yml: |
{{ include "hermes/templates/etc/_logstash.yml.tpl" . | indent 4 }}
