---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wall-e-bin
  namespace: hermes
  labels:
    system: openstack
    service: audit
    component: configuration

data:
  wall-e-start: |
{{ include "hermes/templates/_wall-e-start.tpl" . | indent 4 }}
  create-kibana-indexes.sh: |
{{ include "hermes/templates/_create-kibana-indexes.sh.tpl" . | indent 4 }}
