---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wall-e-etc
  namespace: hermes
  labels:
    system: openstack
    service: audit
    component: configuration

data:
   curator.yml: |
{{ include "hermes/templates/etc/_curator.yml.tpl" . | indent 4 }}
   delete_indices.yml: |
{{ include "hermes/templates/etc/_delete_indices.yml.tpl" . | indent 4 }}
   dot-kibana.json: |
{{ include "hermes/templates/etc/_kibana.json.tpl" . | indent 4 }}
   dot-monitoring-data-2.json: |
{{ include "hermes/templates/etc/_monitoring_data_2.json.tpl" . | indent 4 }}
   dot-monitoring-es-2.json: |
{{ include "hermes/templates/etc/_monitoring_es_2.json.tpl" . | indent 4 }}
