keppel:
  image: sapcc/keppel
  image_tag: latest
  image_pull_policy: Always

  service_password: DEFINED_IN_VALUES_FILE

  issuer:
    key.pem:  DEFINED_IN_VALUES_FILE
    cert.pem: DEFINED_IN_VALUES_FILE
